### ISSUE TITLE
Character encoding for output files

### ISSUE THREAD

**Issue by theblairwhichproject** [bpb27/twitter_scraping#2]
Hello,

I'm a poor linguist trying his hand at Python, and this whole project has been a great resource to me. I'm currently trying to compile a Twitter corpus for my work, but when I run the script to get the metadata, I encounter this error:

`Traceback (most recent call last):
  File "C:/Users/timho/Documents/Programming/Twitter-Corpus/twitter_scraping-master/get_metadata.py", line 93, in <module>
    f.writerow([x["favorite_count"], x["source"], x["text"], x["in_reply_to_screen_name"], x["is_retweet"], x["created_at"], x["retweet_count"], x["id_str"]])
  File "C:\Users\XXX\TwitterCorpus\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60e' in position 115: character maps to <undefined>`

It's obviously related to character encoding; the character causing the problem here is the sunglasses emoji. However, I'm afraid I'm too new to Python to deal with this problem myself.  Would greatly appreciate any help on how to fix this!

**Comment by bpb27** [comment]
quick fix is to just ignore tweets it can't read

change this:
   ```
 for x in data:
        f.writerow([x["favorite_count"], x["source"], x["text"], x["in_reply_to_screen_name"], x["is_retweet"], x["created_at"], x["retweet_count"], x["id_str"]])
```

to this:

```
for x in data:
    try:
        f.writerow([x["favorite_count"], x["source"], x["text"], x["in_reply_to_screen_name"], x["is_retweet"], x["created_at"], x["retweet_count"], x["id_str"]])
    except UnicodeEncodeError:
        pass
```

**Comment by bpb27** [comment]
You could also try changing line 90

change this:
`f = csv.writer(open('{}.csv'.format(user), 'w'))`

to this:
`f = csv.writer(open('{}.csv'.format(user), 'w', encoding='utf-8'))`

**Comment by theblairwhichproject** [comment]
I tried the second approach first (because I wanted to preserve as many tweets as possible) and that worked. Now I feel silly for bothering you with it. Thanks for your help!
